import { Product } from './types';

const STANDARD_WARRANTY = '1-Year CAATG LTD Limited Warranty';
const EXTENDED_WARRANTY = '2-Year Manufacturer Warranty';
const FAST_DELIVERY = 'Free express delivery in 2–4 business days';
const STANDARD_DELIVERY = 'Free standard delivery in 3–6 business days';

export const products: Product[] = [
  // ---------------- SMARTPHONES ----------------
  {
    id: 'p001',
    slug: 'apple-iphone-17-pro-max',
    brand: 'Apple',
    name: 'iPhone 17 Pro Max',
    category: 'smartphones',
    shortDescription: 'Titanium design, A19 Pro chip, 5x telephoto camera.',
    description:
      'The iPhone 17 Pro Max pushes the flagship experience further with a forged titanium frame, the A19 Pro chip for console-level performance, and a completely redesigned camera system built for creators. A brighter Super Retina XDR display and all-day battery life round out Apple’s most capable iPhone yet.',
    price: 1199,
    originalPrice: 1299,
    rating: 4.8,
    reviewCount: 2140,
    stock: 'in-stock',
    badge: 'Bestseller',
    features: [
      '6.9" Super Retina XDR ProMotion display',
      'A19 Pro chip with 6-core GPU',
      '5x telephoto + 48MP Fusion camera system',
      'Titanium frame with Ceramic Shield 2',
      'Up to 33 hours video playback',
    ],
    specs: {
      Display: '6.9" OLED, 120Hz ProMotion',
      Chip: 'Apple A19 Pro',
      Storage: '256GB / 512GB / 1TB',
      Camera: '48MP Main + 48MP Ultra Wide + 12MP 5x Telephoto',
      Battery: 'Up to 33 hours video playback',
      Connectivity: '5G, Wi-Fi 7, Bluetooth 5.4',
      OS: 'iOS 19',
    },
    colorways: ['Titanium Black', 'Titanium Desert', 'Titanium Silver'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2025,
  },
  {
    id: 'p002',
    slug: 'apple-iphone-17',
    brand: 'Apple',
    name: 'iPhone 17',
    category: 'smartphones',
    shortDescription: 'A19 chip, all-day battery, dual-camera system.',
    description:
      'iPhone 17 brings the latest A19 chip, a refined dual-camera system and a stunning edge-to-edge display to Apple’s mainstream lineup, delivering flagship performance at a more accessible price.',
    price: 829,
    rating: 4.6,
    reviewCount: 1580,
    stock: 'in-stock',
    features: [
      '6.3" Super Retina XDR display',
      'A19 chip with 5-core GPU',
      '48MP dual-camera system',
      'Ceramic Shield front and back',
      'Up to 27 hours video playback',
    ],
    specs: {
      Display: '6.3" OLED, 60Hz',
      Chip: 'Apple A19',
      Storage: '128GB / 256GB / 512GB',
      Camera: '48MP Main + 12MP Ultra Wide',
      Battery: 'Up to 27 hours video playback',
      Connectivity: '5G, Wi-Fi 6E, Bluetooth 5.4',
      OS: 'iOS 19',
    },
    colorways: ['Midnight', 'Starlight', 'Sky Blue', 'Product Red'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2025,
  },
  {
    id: 'p003',
    slug: 'samsung-galaxy-s26-ultra',
    brand: 'Samsung',
    name: 'Galaxy S26 Ultra',
    category: 'smartphones',
    shortDescription: '200MP camera, Snapdragon 8 Elite Gen 2, built-in S Pen.',
    description:
      'The Galaxy S26 Ultra is Samsung’s ultimate expression of mobile power, pairing a 200MP quad-camera system with the latest Snapdragon 8 Elite Gen 2 platform, a brilliant 6.9" Dynamic AMOLED 2X display and the precision of the built-in S Pen.',
    price: 1299,
    originalPrice: 1419,
    rating: 4.7,
    reviewCount: 1890,
    stock: 'in-stock',
    badge: 'New',
    features: [
      '6.9" QHD+ Dynamic AMOLED 2X, 120Hz',
      'Snapdragon 8 Elite Gen 2',
      '200MP quad-camera with 10x optical zoom',
      'Built-in S Pen',
      'Galaxy AI photo & productivity tools',
    ],
    specs: {
      Display: '6.9" AMOLED, 120Hz',
      Chip: 'Snapdragon 8 Elite Gen 2',
      Storage: '256GB / 512GB / 1TB',
      Camera: '200MP Main + 50MP Periscope + 12MP Ultra Wide',
      Battery: '5,500 mAh, 45W fast charging',
      Connectivity: '5G, Wi-Fi 7, Bluetooth 5.4',
      OS: 'Android 16, One UI 8',
    },
    colorways: ['Titanium Black', 'Titanium Gray', 'Titanium Violet'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2026,
  },
  {
    id: 'p004',
    slug: 'samsung-galaxy-z-fold-6',
    brand: 'Samsung',
    name: 'Galaxy Z Fold 6',
    category: 'smartphones',
    shortDescription: 'Foldable 7.6" display with multitasking superpowers.',
    description:
      'Galaxy Z Fold 6 transforms from a pocketable phone into a 7.6" tablet-class display, purpose-built for multitasking, productivity and immersive media with a strengthened hinge and Armor Aluminum frame.',
    price: 1899,
    rating: 4.5,
    reviewCount: 640,
    stock: 'low-stock',
    features: [
      '7.6" foldable Dynamic AMOLED main display',
      '6.3" cover display',
      'Snapdragon 8 Gen 3 for Galaxy',
      'Multi-window multitasking',
      'IPX8 water resistance',
    ],
    specs: {
      Display: '7.6" foldable AMOLED / 6.3" cover',
      Chip: 'Snapdragon 8 Gen 3 for Galaxy',
      Storage: '256GB / 512GB',
      Camera: '50MP Main + 12MP Ultra Wide + 10MP Telephoto',
      Battery: '4,400 mAh',
      Connectivity: '5G, Wi-Fi 7, Bluetooth 5.3',
      OS: 'Android 16, One UI 8',
    },
    colorways: ['Silver Shadow', 'Navy'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2025,
  },
  {
    id: 'p005',
    slug: 'xiaomi-15-pro',
    brand: 'Xiaomi',
    name: 'Xiaomi 15 Pro',
    category: 'smartphones',
    shortDescription: 'Leica-tuned optics, Snapdragon 8 Elite, 90W charging.',
    description:
      'Xiaomi 15 Pro pairs Leica-engineered optics with flagship Snapdragon performance and blistering 90W HyperCharge, wrapped in a refined ceramic-and-glass body.',
    price: 999,
    originalPrice: 1099,
    rating: 4.5,
    reviewCount: 720,
    stock: 'in-stock',
    features: [
      '6.73" 2K LTPO AMOLED, 120Hz',
      'Snapdragon 8 Elite',
      'Leica triple-camera system',
      '90W HyperCharge wired + 50W wireless',
      'IP68 water & dust resistance',
    ],
    specs: {
      Display: '6.73" AMOLED, 120Hz',
      Chip: 'Snapdragon 8 Elite',
      Storage: '256GB / 512GB',
      Camera: '50MP Leica Triple Camera',
      Battery: '6,100 mAh, 90W wired charging',
      Connectivity: '5G, Wi-Fi 7, Bluetooth 5.4',
      OS: 'Android 15, HyperOS 2',
    },
    colorways: ['Black', 'White', 'Green'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2025,
  },
  {
    id: 'p006',
    slug: 'sony-xperia-1-vi',
    brand: 'Sony',
    name: 'Xperia 1 VI',
    category: 'smartphones',
    shortDescription: 'Creator-grade cameras with real optical zoom.',
    description:
      'Xperia 1 VI is built for creators, combining a true optical zoom lens, professional color science from Sony’s Alpha camera lineup, and a stunning 21:9 display tuned for content creation.',
    price: 1099,
    rating: 4.3,
    reviewCount: 310,
    stock: 'in-stock',
    features: [
      '6.5" 21:9 OLED display',
      'Snapdragon 8 Gen 3',
      'Triple camera with true optical zoom',
      'Dedicated shutter button',
      'Dolby Atmos stereo speakers',
    ],
    specs: {
      Display: '6.5" OLED, 21:9, 120Hz',
      Chip: 'Snapdragon 8 Gen 3',
      Storage: '256GB',
      Camera: '48MP Triple Camera, true optical zoom',
      Battery: '5,000 mAh',
      Connectivity: '5G, Wi-Fi 7, Bluetooth 5.3',
      OS: 'Android 14',
    },
    colorways: ['Black', 'Platinum Silver'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },

  // ---------------- LAPTOPS ----------------
  {
    id: 'p010',
    slug: 'apple-macbook-pro-16-m4-pro',
    brand: 'Apple',
    name: 'MacBook Pro 16" M4 Pro',
    category: 'laptops',
    shortDescription: 'M4 Pro chip, Liquid Retina XDR display, 22-hour battery.',
    description:
      'The MacBook Pro 16" with M4 Pro delivers extraordinary performance for professional workflows — video editing, 3D rendering, and software development — backed by a stunning Liquid Retina XDR display and all-day battery life.',
    price: 2499,
    rating: 4.9,
    reviewCount: 980,
    stock: 'in-stock',
    badge: 'Editor\'s Pick',
    features: [
      '16.2" Liquid Retina XDR display',
      'Apple M4 Pro, 14-core CPU / 20-core GPU',
      'Up to 22 hours battery life',
      '1080p FaceTime HD camera',
      'Six-speaker sound system with Spatial Audio',
    ],
    specs: {
      Display: '16.2" Liquid Retina XDR, mini-LED',
      Chip: 'Apple M4 Pro',
      Memory: '24GB / 36GB / 48GB unified memory',
      Storage: '512GB – 2TB SSD',
      Battery: 'Up to 22 hours',
      Ports: '3x Thunderbolt 5, HDMI, SDXC, MagSafe 3',
    },
    colorways: ['Space Black', 'Silver'],
    warranty: EXTENDED_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2024,
  },
  {
    id: 'p011',
    slug: 'apple-macbook-air-15-m3',
    brand: 'Apple',
    name: 'MacBook Air 15" M3',
    category: 'laptops',
    shortDescription: 'Strikingly thin, fanless M3 performance, 18-hour battery.',
    description:
      'MacBook Air 15" with M3 combines a spacious Liquid Retina display, silent fanless design and remarkable battery life into Apple’s thinnest and lightest 15-inch laptop.',
    price: 1299,
    originalPrice: 1399,
    rating: 4.7,
    reviewCount: 1420,
    stock: 'in-stock',
    features: [
      '15.3" Liquid Retina display',
      'Apple M3 chip, 8-core CPU / 10-core GPU',
      'Up to 18 hours battery life',
      'Fanless silent design',
      '1080p FaceTime HD camera',
    ],
    specs: {
      Display: '15.3" Liquid Retina, IPS',
      Chip: 'Apple M3',
      Memory: '8GB / 16GB / 24GB unified memory',
      Storage: '256GB – 1TB SSD',
      Battery: 'Up to 18 hours',
      Ports: '2x Thunderbolt, MagSafe 3, 3.5mm jack',
    },
    colorways: ['Midnight', 'Starlight', 'Space Gray', 'Silver'],
    warranty: EXTENDED_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p012',
    slug: 'hp-spectre-x360-14',
    brand: 'HP',
    name: 'Spectre x360 14',
    category: 'laptops',
    shortDescription: 'Convertible 2-in-1 with OLED display and gem-cut design.',
    description:
      'The HP Spectre x360 14 blends a striking gem-cut chassis with a vivid 3K2K OLED touch display and 360° hinge, making it equally at home as a laptop, tablet or presentation display.',
    price: 1449,
    originalPrice: 1599,
    rating: 4.6,
    reviewCount: 860,
    stock: 'in-stock',
    features: [
      '14" 3K2K OLED touchscreen, 2-in-1 convertible',
      'Intel Core Ultra 7 processor',
      'HP Tilt Pen included',
      'Bang & Olufsen quad speakers',
      'Up to 17 hours battery life',
    ],
    specs: {
      Display: '14" 2880x1800 OLED touch',
      CPU: 'Intel Core Ultra 7 155H',
      Memory: '16GB / 32GB LPDDR5',
      Storage: '512GB – 2TB SSD',
      GPU: 'Intel Arc Graphics',
      Battery: 'Up to 17 hours',
    },
    colorways: ['Nocturne Blue', 'Nightfall Black'],
    warranty: EXTENDED_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p013',
    slug: 'lenovo-legion-pro-7i',
    brand: 'Lenovo',
    name: 'Legion Pro 7i',
    category: 'laptops',
    shortDescription: 'RTX 5080 graphics, 240Hz display, elite gaming power.',
    description:
      'Legion Pro 7i is Lenovo’s flagship gaming laptop, pairing Intel’s fastest mobile processors with NVIDIA RTX 50-series graphics and a Legion Coldfront cooling system for sustained high-refresh performance.',
    price: 2199,
    rating: 4.7,
    reviewCount: 540,
    stock: 'in-stock',
    badge: 'Bestseller',
    features: [
      '16" WQXGA display, 240Hz',
      'Intel Core i9-14900HX',
      'NVIDIA GeForce RTX 5080 laptop GPU',
      'Legion Coldfront 5.0 cooling',
      'Per-key RGB keyboard',
    ],
    specs: {
      Display: '16" 2560x1600, 240Hz',
      CPU: 'Intel Core i9-14900HX',
      GPU: 'NVIDIA GeForce RTX 5080, 16GB',
      Memory: '32GB DDR5',
      Storage: '1TB – 2TB SSD',
      Battery: '99.9Wh',
    },
    colorways: ['Onyx Grey'],
    warranty: EXTENDED_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2025,
  },
  {
    id: 'p014',
    slug: 'asus-rog-zephyrus-g14',
    brand: 'ASUS',
    name: 'ROG Zephyrus G14',
    category: 'laptops',
    shortDescription: 'Compact 14" powerhouse for gaming and creation.',
    description:
      'The ASUS ROG Zephyrus G14 packs desktop-class RTX graphics and AMD Ryzen AI performance into an ultra-portable magnesium-alloy chassis with a stunning Nebula Display.',
    price: 1849,
    originalPrice: 1999,
    rating: 4.6,
    reviewCount: 710,
    stock: 'in-stock',
    features: [
      '14" 2.8K Nebula Display, 120Hz',
      'AMD Ryzen AI 9 HX 370',
      'NVIDIA GeForce RTX 4070 laptop GPU',
      'AniMe Vision LED lid',
      'Up to 10 hours battery life',
    ],
    specs: {
      Display: '14" 2880x1800, 120Hz',
      CPU: 'AMD Ryzen AI 9 HX 370',
      GPU: 'NVIDIA GeForce RTX 4070, 8GB',
      Memory: '32GB LPDDR5X',
      Storage: '1TB SSD',
      Battery: '73Wh',
    },
    colorways: ['Eclipse Grey', 'Platinum White'],
    warranty: EXTENDED_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p015',
    slug: 'dell-xps-14',
    brand: 'Dell',
    name: 'XPS 14',
    category: 'laptops',
    shortDescription: 'Edge-to-edge InfinityEdge display, premium CNC aluminum build.',
    description:
      'Dell XPS 14 continues the XPS legacy of minimalist design and premium materials, featuring a nearly borderless InfinityEdge display and a capacitive haptic touchpad milled from a single piece of aluminum.',
    price: 1699,
    rating: 4.5,
    reviewCount: 490,
    stock: 'low-stock',
    features: [
      '14.5" 3.2K OLED InfinityEdge display',
      'Intel Core Ultra 7',
      'Zero-lattice keyboard',
      'Haptic touchpad',
      'Quad speaker design tuned by experts',
    ],
    specs: {
      Display: '14.5" 3200x2000 OLED',
      CPU: 'Intel Core Ultra 7 155H',
      GPU: 'NVIDIA GeForce RTX 4050',
      Memory: '16GB / 32GB LPDDR5X',
      Storage: '512GB – 1TB SSD',
      Battery: 'Up to 13 hours',
    },
    colorways: ['Platinum', 'Graphite'],
    warranty: EXTENDED_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p016',
    slug: 'acer-predator-helios-18',
    brand: 'Acer',
    name: 'Predator Helios 18',
    category: 'laptops',
    shortDescription: 'Mini-LED display, desktop-class cooling, 18" gaming beast.',
    description:
      'The Acer Predator Helios 18 is built for serious gamers, with a Mini-LED display, 5th Gen AeroBlade fans and enough thermal headroom for extended high-performance sessions.',
    price: 2399,
    originalPrice: 2599,
    rating: 4.4,
    reviewCount: 260,
    stock: 'in-stock',
    features: [
      '18" Mini-LED display, 250Hz',
      'Intel Core i9-14900HX',
      'NVIDIA GeForce RTX 4080 laptop GPU',
      '5th Gen AeroBlade 3D fans',
      'Per-key RGB with PredatorSense',
    ],
    specs: {
      Display: '18" 2560x1600 Mini-LED, 250Hz',
      CPU: 'Intel Core i9-14900HX',
      GPU: 'NVIDIA GeForce RTX 4080, 12GB',
      Memory: '32GB DDR5',
      Storage: '2TB SSD (2x1TB RAID 0)',
      Battery: '99.98Wh',
    },
    colorways: ['Abyssal Black'],
    warranty: EXTENDED_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },

  // ---------------- TABLETS ----------------
  {
    id: 'p020',
    slug: 'apple-ipad-pro-13-m4',
    brand: 'Apple',
    name: 'iPad Pro 13" M4',
    category: 'tablets',
    shortDescription: 'Ultra Retina XDR tandem OLED, thinnest Apple device ever.',
    description:
      'iPad Pro 13" with M4 introduces the Ultra Retina XDR display using tandem OLED technology, wrapped in Apple’s thinnest design ever, delivering desktop-class performance in a remarkably portable form.',
    price: 1299,
    rating: 4.8,
    reviewCount: 1120,
    stock: 'in-stock',
    badge: 'New',
    features: [
      '13" Ultra Retina XDR tandem OLED',
      'Apple M4 chip',
      'Compatible with Apple Pencil Pro',
      'Landscape 12MP ultra-wide front camera',
      'Face ID',
    ],
    specs: {
      Display: '13" tandem OLED, 120Hz ProMotion',
      Chip: 'Apple M4',
      Storage: '256GB – 2TB',
      Camera: '12MP Wide + LiDAR Scanner',
      Connectivity: 'Wi-Fi 6E, optional 5G',
      OS: 'iPadOS 18',
    },
    colorways: ['Space Black', 'Silver'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2024,
  },
  {
    id: 'p021',
    slug: 'samsung-galaxy-tab-s10-ultra',
    brand: 'Samsung',
    name: 'Galaxy Tab S10 Ultra',
    category: 'tablets',
    shortDescription: '14.6" AMOLED canvas with S Pen included.',
    description:
      'Galaxy Tab S10 Ultra offers a massive 14.6" Dynamic AMOLED 2X display, an included S Pen and DeX desktop mode, making it a genuine laptop replacement for creative professionals.',
    price: 1199,
    originalPrice: 1299,
    rating: 4.6,
    reviewCount: 480,
    stock: 'in-stock',
    features: [
      '14.6" Dynamic AMOLED 2X display',
      'MediaTek Dimensity 9300+',
      'S Pen included',
      'Samsung DeX desktop mode',
      'Quad AKG speakers',
    ],
    specs: {
      Display: '14.6" AMOLED, 120Hz',
      Chip: 'MediaTek Dimensity 9300+',
      Storage: '256GB / 512GB / 1TB',
      Camera: '13MP + 8MP Ultra Wide',
      Battery: '11,200 mAh',
      OS: 'Android 15, One UI 7',
    },
    colorways: ['Moonstone Gray', 'Platinum Silver'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p022',
    slug: 'apple-ipad-air',
    brand: 'Apple',
    name: 'iPad Air',
    category: 'tablets',
    shortDescription: 'M2 chip performance in a light, versatile design.',
    description:
      'iPad Air brings M2-powered performance to a lightweight, do-everything tablet, available in an all-new 13" size alongside the classic 11", perfect for work, study and creativity.',
    price: 599,
    rating: 4.7,
    reviewCount: 1650,
    stock: 'in-stock',
    features: [
      '11" or 13" Liquid Retina display',
      'Apple M2 chip',
      'Apple Pencil Pro support',
      '12MP landscape front camera',
      'Touch ID in top button',
    ],
    specs: {
      Display: '11" / 13" Liquid Retina, IPS',
      Chip: 'Apple M2',
      Storage: '128GB – 1TB',
      Camera: '12MP Wide',
      Connectivity: 'Wi-Fi 6, optional 5G',
      OS: 'iPadOS 18',
    },
    colorways: ['Space Gray', 'Blue', 'Purple', 'Starlight'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p023',
    slug: 'lenovo-tab-extreme',
    brand: 'Lenovo',
    name: 'Tab Extreme',
    category: 'tablets',
    shortDescription: '14.5" 3K OLED with detachable keyboard and pen.',
    description:
      'Lenovo Tab Extreme delivers a cinema-grade 14.5" 3K OLED display and bundled precision pen, ideal for entertainment, note-taking and light productivity on the go.',
    price: 749,
    originalPrice: 849,
    rating: 4.3,
    reviewCount: 210,
    stock: 'in-stock',
    features: [
      '14.5" 3K OLED display',
      'MediaTek Dimensity 9000',
      'Lenovo Precision Pen 3 included',
      'JBL quad speakers with Dolby Atmos',
      '12,300 mAh battery',
    ],
    specs: {
      Display: '14.5" 3000x1876 OLED',
      Chip: 'MediaTek Dimensity 9000',
      Storage: '256GB',
      Camera: '13MP + 5MP Ultra Wide',
      Battery: '12,300 mAh',
      OS: 'Android 13',
    },
    colorways: ['Storm Grey'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2023,
  },
  {
    id: 'p024',
    slug: 'xiaomi-pad-7-pro',
    brand: 'Xiaomi',
    name: 'Pad 7 Pro',
    category: 'tablets',
    shortDescription: 'Flagship performance at a compelling price.',
    description:
      'Xiaomi Pad 7 Pro combines a sharp 3K flat display, Snapdragon flagship power and a metal unibody design for an excellent everyday and entertainment tablet.',
    price: 549,
    rating: 4.4,
    reviewCount: 330,
    stock: 'in-stock',
    features: [
      '12.5" 3.2K LCD, 144Hz',
      'Snapdragon 8s Gen 3',
      'Quad speakers tuned by Harman Kardon',
      'Xiaomi Smart Pen support',
      '8,850 mAh battery',
    ],
    specs: {
      Display: '12.5" 3200x2136, 144Hz',
      Chip: 'Snapdragon 8s Gen 3',
      Storage: '256GB / 512GB',
      Camera: '13MP Main',
      Battery: '8,850 mAh, 67W charging',
      OS: 'Android 14, HyperOS',
    },
    colorways: ['Black', 'White'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },

  // ---------------- GAMING ----------------
  {
    id: 'p030',
    slug: 'sony-playstation-5-pro',
    brand: 'Sony',
    name: 'PlayStation 5 Pro',
    category: 'gaming',
    shortDescription: 'Enhanced GPU, ray tracing and PSSR upscaling.',
    description:
      'PlayStation 5 Pro delivers a major leap in graphics fidelity with an enhanced GPU, advanced ray tracing capabilities, and PlayStation Spectral Super Resolution for sharper, more detailed worlds.',
    price: 699,
    rating: 4.8,
    reviewCount: 3200,
    stock: 'in-stock',
    badge: 'Bestseller',
    features: [
      '45% faster GPU rendering than PS5',
      'Advanced ray tracing',
      'PSSR AI upscaling',
      '2TB SSD storage',
      'Backward compatible with PS5 & PS4 titles',
    ],
    specs: {
      Storage: '2TB SSD',
      Resolution: 'Up to 8K, 120fps',
      GPU: 'Custom RDNA architecture, enhanced',
      Connectivity: 'Wi-Fi 6, Bluetooth 5.3, Gigabit Ethernet',
      Ports: '2x USB-C, USB-A, HDMI 2.1',
    },
    colorways: ['White'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2024,
  },
  {
    id: 'p031',
    slug: 'microsoft-xbox-series-x',
    brand: 'Microsoft',
    name: 'Xbox Series X',
    category: 'gaming',
    shortDescription: 'True 4K gaming at up to 120fps with Quick Resume.',
    description:
      'Xbox Series X is Microsoft’s most powerful console, delivering true 4K gaming, ultra-fast load times with a custom NVMe SSD, and access to Xbox Game Pass’ vast library.',
    price: 499,
    rating: 4.7,
    reviewCount: 2760,
    stock: 'in-stock',
    features: [
      '12 teraflops of GPU performance',
      'True 4K gaming, up to 120fps',
      '1TB custom NVMe SSD',
      'Quick Resume for multiple games',
      'Xbox Game Pass compatible',
    ],
    specs: {
      Storage: '1TB NVMe SSD',
      Resolution: 'Up to 4K, 120fps',
      GPU: '12 TFLOPS, RDNA 2',
      Connectivity: 'Wi-Fi, Bluetooth, Gigabit Ethernet',
      Ports: '3x USB-A, HDMI 2.1',
    },
    colorways: ['Matte Black'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2020,
  },
  {
    id: 'p032',
    slug: 'nintendo-switch-2',
    brand: 'Nintendo',
    name: 'Switch 2',
    category: 'gaming',
    shortDescription: 'Bigger screen, magnetic Joy-Cons, backward compatible.',
    description:
      'Nintendo Switch 2 upgrades everything gamers love about the original with a larger 7.9" LCD display, magnetically attaching Joy-Con 2 controllers, and full backward compatibility with Switch titles.',
    price: 449,
    rating: 4.6,
    reviewCount: 1290,
    stock: 'low-stock',
    badge: 'New',
    features: [
      '7.9" 1080p LCD display',
      'Magnetic Joy-Con 2 controllers',
      'Backward compatible with Switch games',
      'Enhanced dock with improved cooling',
      'Up to 6 hours battery life',
    ],
    specs: {
      Display: '7.9" LCD, 1080p (docked 4K)',
      Storage: '256GB internal, microSD expandable',
      Battery: 'Up to 6 hours',
      Controllers: 'Joy-Con 2 (magnetic attach)',
      Connectivity: 'Wi-Fi 6, Bluetooth',
    },
    colorways: ['Black'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2025,
  },
  {
    id: 'p033',
    slug: 'asus-rog-ally-x',
    brand: 'ASUS',
    name: 'ROG Ally X',
    category: 'gaming',
    shortDescription: 'Handheld gaming PC with Windows 11 and AMD Ryzen Z1 Extreme.',
    description:
      'ROG Ally X packs a full Windows 11 gaming PC into a handheld form factor, powered by the AMD Ryzen Z1 Extreme processor with a larger battery and improved ergonomics for extended play sessions.',
    price: 799,
    originalPrice: 899,
    rating: 4.4,
    reviewCount: 380,
    stock: 'in-stock',
    features: [
      '7" FHD 120Hz display',
      'AMD Ryzen Z1 Extreme',
      '24GB LPDDR5X memory',
      '80Wh battery, nearly 2x original Ally',
      'Windows 11 with full PC game library access',
    ],
    specs: {
      Display: '7" 1920x1080, 120Hz',
      CPU: 'AMD Ryzen Z1 Extreme',
      Memory: '24GB LPDDR5X',
      Storage: '1TB SSD',
      Battery: '80Wh',
      OS: 'Windows 11',
    },
    colorways: ['Black'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p034',
    slug: 'razer-kishi-v3',
    brand: 'Razer',
    name: 'Kishi V3 Mobile Controller',
    category: 'gaming',
    shortDescription: 'Console-quality controls for your smartphone.',
    description:
      'Razer Kishi V3 clips onto your smartphone to deliver console-quality analog sticks, triggers and buttons for cloud gaming and mobile titles, with pass-through charging for uninterrupted sessions.',
    price: 99,
    rating: 4.3,
    reviewCount: 640,
    stock: 'in-stock',
    features: [
      'Console-grade analog sticks and triggers',
      'USB-C pass-through charging',
      'Universal fit for most smartphones',
      'Plug-and-play, no Bluetooth pairing',
      'Compatible with Xbox Game Pass, GeForce NOW',
    ],
    specs: {
      Connectivity: 'USB-C direct connect',
      Compatibility: 'Android & iPhone (USB-C)',
      Weight: '164g',
      Charging: 'Pass-through USB-C',
    },
    colorways: ['Black'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p035',
    slug: 'logitech-g-pro-x-superlight-2',
    brand: 'Logitech',
    name: 'G Pro X Superlight 2 Gaming Mouse',
    category: 'gaming',
    shortDescription: 'Ultra-lightweight 60g esports mouse, 32K DPI sensor.',
    description:
      'The Logitech G Pro X Superlight 2 is trusted by professional esports athletes worldwide, weighing just 60 grams with a flawless HERO 2 32K DPI sensor and up to 95 hours of battery life.',
    price: 159,
    rating: 4.9,
    reviewCount: 1980,
    stock: 'in-stock',
    badge: 'Bestseller',
    features: [
      '60g ultra-lightweight design',
      'HERO 2 sensor, up to 32,000 DPI',
      'Up to 95 hours battery life',
      'LIGHTSPEED wireless technology',
      'Zero additive PTFE feet',
    ],
    specs: {
      Sensor: 'HERO 2, 32,000 DPI',
      Weight: '60g',
      Battery: 'Up to 95 hours',
      Connectivity: 'LIGHTSPEED wireless, USB-C',
      Buttons: '5 programmable',
    },
    colorways: ['Black', 'White', 'Pink'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2023,
  },

  // ---------------- MONITORS ----------------
  {
    id: 'p040',
    slug: 'samsung-odyssey-oled-g9',
    brand: 'Samsung',
    name: 'Odyssey OLED G9',
    category: 'monitors',
    shortDescription: '49" curved dual-QHD OLED, 240Hz ultrawide immersion.',
    description:
      'The Samsung Odyssey OLED G9 wraps around your field of view with a 49" 1000R curved OLED panel, dual-QHD resolution and a blistering 240Hz refresh rate for the ultimate ultrawide gaming setup.',
    price: 1499,
    originalPrice: 1799,
    rating: 4.7,
    reviewCount: 420,
    stock: 'in-stock',
    badge: 'Limited',
    features: [
      '49" 1000R curved OLED panel',
      '5120x1440 Dual QHD resolution',
      '240Hz refresh rate, 0.03ms response',
      'NVIDIA G-SYNC & AMD FreeSync Premium Pro',
      'Height, tilt & swivel adjustable stand',
    ],
    specs: {
      'Panel Size': '49" curved (1000R)',
      Resolution: '5120x1440 (Dual QHD)',
      'Refresh Rate': '240Hz',
      'Response Time': '0.03ms (GtG)',
      Ports: '2x HDMI 2.1, 1x DisplayPort 1.4, USB hub',
    },
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    isFeatured: true,
    releaseYear: 2024,
  },
  {
    id: 'p041',
    slug: 'asus-rog-swift-oled-pg27aqdm',
    brand: 'ASUS',
    name: 'ROG Swift OLED PG27AQDM',
    category: 'monitors',
    shortDescription: '27" QHD OLED, 240Hz, near-instant pixel response.',
    description:
      'The ASUS ROG Swift OLED PG27AQDM delivers perfect blacks and razor-sharp motion clarity with a 27" QHD OLED panel running at 240Hz, engineered for competitive and cinematic gaming alike.',
    price: 899,
    rating: 4.8,
    reviewCount: 560,
    stock: 'in-stock',
    features: [
      '27" QHD (2560x1440) OLED panel',
      '240Hz refresh rate',
      '0.03ms response time',
      'NVIDIA G-SYNC compatible',
      'Anti-glare coating with heatsink design',
    ],
    specs: {
      'Panel Size': '27"',
      Resolution: '2560x1440 (QHD)',
      'Refresh Rate': '240Hz',
      'Response Time': '0.03ms (GtG)',
      Ports: 'DisplayPort 1.4, 2x HDMI 2.1, USB hub',
    },
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2023,
  },
  {
    id: 'p042',
    slug: 'dell-ultrasharp-u2723qe',
    brand: 'Dell',
    name: 'UltraSharp U2723QE',
    category: 'monitors',
    shortDescription: '27" 4K IPS Black with factory color calibration.',
    description:
      'Dell UltraSharp U2723QE is engineered for creative professionals, featuring IPS Black technology for deeper contrast, 4K resolution and factory color calibration covering 98% DCI-P3.',
    price: 649,
    rating: 4.6,
    reviewCount: 340,
    stock: 'in-stock',
    features: [
      '27" 4K UHD IPS Black panel',
      '2000:1 contrast ratio',
      '98% DCI-P3 color coverage, factory calibrated',
      'Built-in KVM switch and USB-C hub',
      '90W USB-C power delivery',
    ],
    specs: {
      'Panel Size': '27"',
      Resolution: '3840x2160 (4K UHD)',
      Contrast: '2000:1 (IPS Black)',
      'Color Coverage': '98% DCI-P3',
      Ports: 'USB-C (90W PD), DisplayPort, HDMI, KVM',
    },
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2022,
  },
  {
    id: 'p043',
    slug: 'acer-predator-x32-fp',
    brand: 'Acer',
    name: 'Predator X32 FP',
    category: 'monitors',
    shortDescription: '32" 4K mini-LED, 160Hz, DisplayHDR 1000.',
    description:
      'The Acer Predator X32 FP combines 4K sharpness with mini-LED local dimming and a 160Hz refresh rate, certified for DisplayHDR 1000 to deliver breathtaking contrast and vivid gaming visuals.',
    price: 1199,
    originalPrice: 1349,
    rating: 4.5,
    reviewCount: 190,
    stock: 'low-stock',
    features: [
      '32" 4K UHD mini-LED panel',
      '160Hz overclocked refresh rate',
      'DisplayHDR 1000 certified',
      'NVIDIA G-SYNC Ultimate',
      '1152-zone local dimming',
    ],
    specs: {
      'Panel Size': '32"',
      Resolution: '3840x2160 (4K UHD)',
      'Refresh Rate': '160Hz (overclocked)',
      HDR: 'DisplayHDR 1000',
      Ports: 'DisplayPort 1.4, 2x HDMI 2.1, USB hub',
    },
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2023,
  },
  {
    id: 'p044',
    slug: 'hp-omen-27qs',
    brand: 'HP',
    name: 'Omen 27qs',
    category: 'monitors',
    shortDescription: 'QHD 240Hz Fast IPS for competitive gaming.',
    description:
      'HP Omen 27qs delivers fluid, tear-free QHD gaming at 240Hz with a Fast IPS panel that balances vibrant color accuracy and rapid response time for a well-rounded competitive setup.',
    price: 549,
    rating: 4.4,
    reviewCount: 260,
    stock: 'in-stock',
    features: [
      '27" QHD Fast IPS panel',
      '240Hz refresh rate, 1ms response',
      'AMD FreeSync Premium',
      '99% sRGB color coverage',
      'Adjustable height, tilt, swivel and pivot stand',
    ],
    specs: {
      'Panel Size': '27"',
      Resolution: '2560x1440 (QHD)',
      'Refresh Rate': '240Hz',
      'Response Time': '1ms (GtG)',
      Ports: 'DisplayPort 1.4, 2x HDMI 2.1',
    },
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2023,
  },

  // ---------------- AUDIO ----------------
  {
    id: 'p050',
    slug: 'sony-wh-1000xm6',
    brand: 'Sony',
    name: 'WH-1000XM6',
    category: 'audio',
    shortDescription: 'Industry-leading noise cancellation, 30-hour battery.',
    description:
      'The Sony WH-1000XM6 refines Sony’s legendary noise-cancelling headphones with a new HD Noise Cancelling Processor, richer sound tuning and effortless all-day comfort.',
    price: 399,
    originalPrice: 449,
    rating: 4.8,
    reviewCount: 2450,
    stock: 'in-stock',
    badge: 'Bestseller',
    features: [
      'Industry-leading active noise cancellation',
      'Up to 30 hours battery life (ANC on)',
      'Multipoint Bluetooth connection',
      'Adaptive Sound Control',
      'Speak-to-Chat automatic pause',
    ],
    specs: {
      Type: 'Over-ear, closed-back wireless',
      Battery: 'Up to 30 hours (ANC on)',
      Connectivity: 'Bluetooth 5.3, multipoint',
      Driver: '30mm dynamic driver',
      Weight: '250g',
    },
    colorways: ['Black', 'Platinum Silver', 'Midnight Blue'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2025,
  },
  {
    id: 'p051',
    slug: 'apple-airpods-pro-3',
    brand: 'Apple',
    name: 'AirPods Pro 3',
    category: 'audio',
    shortDescription: 'Adaptive Audio, heart-rate sensing, richer bass.',
    description:
      'AirPods Pro 3 introduce Adaptive Audio that blends transparency and noise cancellation in real time, alongside a redesigned acoustic architecture and built-in heart-rate sensing for workouts.',
    price: 249,
    rating: 4.7,
    reviewCount: 3100,
    stock: 'in-stock',
    features: [
      'Adaptive Audio with Personalized Volume',
      'Up to 2x stronger Active Noise Cancellation',
      'Heart rate sensing',
      'Up to 8 hours listening time per charge',
      'IP57 dust and water resistance',
    ],
    specs: {
      Type: 'In-ear wireless earbuds',
      Battery: 'Up to 8 hours (24 with case)',
      Connectivity: 'Bluetooth 5.4',
      Chip: 'Apple H3',
      'Water Resistance': 'IP57',
    },
    colorways: ['White'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2025,
  },
  {
    id: 'p052',
    slug: 'jbl-charge-6',
    brand: 'JBL',
    name: 'Charge 6 Portable Speaker',
    category: 'audio',
    shortDescription: 'Bold JBL Pro Sound with 24-hour playtime and power bank.',
    description:
      'JBL Charge 6 delivers bold, room-filling sound with deep bass in a rugged, waterproof body, plus a built-in power bank to keep your devices charged on the go.',
    price: 199,
    rating: 4.6,
    reviewCount: 1340,
    stock: 'in-stock',
    features: [
      'JBL Pro Sound with powerful bass',
      'Up to 24 hours playtime',
      'IP68 waterproof & dustproof',
      'Built-in power bank (USB-C out)',
      'PartyBoost for multi-speaker pairing',
    ],
    specs: {
      Type: 'Portable Bluetooth speaker',
      Battery: 'Up to 24 hours',
      Connectivity: 'Bluetooth 5.3, USB-C',
      'Water Resistance': 'IP68',
      Weight: '990g',
    },
    colorways: ['Black', 'Blue', 'Camo'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2025,
  },
  {
    id: 'p053',
    slug: 'bose-quietcomfort-ultra-headphones',
    brand: 'Bose',
    name: 'QuietComfort Ultra Headphones',
    category: 'audio',
    shortDescription: 'Immersive spatial audio with world-class quiet.',
    description:
      'Bose QuietComfort Ultra Headphones pair the brand’s best-in-class noise cancellation with Bose Immersive Audio, wrapping every listen in rich, spatial sound and premium all-day comfort.',
    price: 429,
    rating: 4.7,
    reviewCount: 980,
    stock: 'in-stock',
    features: [
      'World-class active noise cancellation',
      'Bose Immersive Audio with head tracking',
      'Up to 24 hours battery life',
      'Adjustable ANC and Aware modes',
      'Plush memory-foam ear cushions',
    ],
    specs: {
      Type: 'Over-ear, closed-back wireless',
      Battery: 'Up to 24 hours (ANC on)',
      Connectivity: 'Bluetooth 5.3, multipoint',
      Weight: '253g',
    },
    colorways: ['Black', 'White Smoke', 'Sandstone'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2023,
  },
  {
    id: 'p054',
    slug: 'logitech-g733-gaming-headset',
    brand: 'Logitech',
    name: 'G733 Lightspeed Gaming Headset',
    category: 'audio',
    shortDescription: 'Lightweight wireless headset with customizable RGB.',
    description:
      'Logitech G733 combines LIGHTSPEED wireless technology, DTS Headphone:X 2.0 surround sound and a suspension headband design for lag-free comfort during marathon gaming sessions.',
    price: 129,
    originalPrice: 149,
    rating: 4.5,
    reviewCount: 2200,
    stock: 'in-stock',
    features: [
      'LIGHTSPEED wireless technology',
      'DTS Headphone:X 2.0 spatial audio',
      'Up to 29 hours battery life',
      'Detachable Blue VO!CE microphone',
      'Customizable LIGHTSYNC RGB',
    ],
    specs: {
      Type: 'Over-ear wireless gaming headset',
      Battery: 'Up to 29 hours',
      Connectivity: 'LIGHTSPEED 2.4GHz',
      Weight: '278g',
    },
    colorways: ['Black', 'White', 'Lilac'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2021,
  },
  {
    id: 'p055',
    slug: 'sony-wf-1000xm5',
    brand: 'Sony',
    name: 'WF-1000XM5 Earbuds',
    category: 'audio',
    shortDescription: 'Compact design, industry-leading noise cancellation.',
    description:
      'Sony WF-1000XM5 shrinks the flagship noise-cancelling experience into a more compact, comfortable earbud, powered by dual processors for exceptional call quality and sound.',
    price: 299,
    originalPrice: 329,
    rating: 4.6,
    reviewCount: 1760,
    stock: 'in-stock',
    features: [
      'Industry-leading noise cancellation',
      'Integrated Processor V2 + HD Noise Cancelling Processor QN2e',
      'Up to 8 hours battery life (24 with case)',
      'Multipoint connection',
      'Adaptive Sound Control',
    ],
    specs: {
      Type: 'In-ear wireless earbuds',
      Battery: 'Up to 8 hours (24 with case)',
      Connectivity: 'Bluetooth 5.3, multipoint',
      'Water Resistance': 'IPX4',
    },
    colorways: ['Black', 'Silver'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2023,
  },
  {
    id: 'p056',
    slug: 'jbl-live-770nc',
    brand: 'JBL',
    name: 'Live 770NC',
    category: 'audio',
    shortDescription: 'Adaptive noise cancellation with signature JBL sound.',
    description:
      'JBL Live 770NC delivers punchy, signature JBL sound with adaptive noise cancellation that adjusts to your environment, plus a lightweight, foldable design for everyday comfort.',
    price: 179,
    rating: 4.3,
    reviewCount: 540,
    stock: 'in-stock',
    features: [
      'Adaptive Noise Cancelling',
      'Up to 65 hours battery life',
      'True Adaptive Ambient Aware',
      'JBL Headphones App with EQ',
      'Foldable, lightweight design',
    ],
    specs: {
      Type: 'Over-ear, closed-back wireless',
      Battery: 'Up to 65 hours (ANC off)',
      Connectivity: 'Bluetooth 5.3',
      Weight: '219g',
    },
    colorways: ['Black', 'Blue', 'White'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2023,
  },

  // ---------------- SMARTWATCHES ----------------
  {
    id: 'p060',
    slug: 'apple-watch-series-11',
    brand: 'Apple',
    name: 'Apple Watch Series 11',
    category: 'smartwatches',
    shortDescription: 'Advanced health sensors, brighter always-on display.',
    description:
      'Apple Watch Series 11 introduces new health insights including hypertension notifications, wrapped in a thinner design with a brighter always-on Retina display and faster charging.',
    price: 429,
    rating: 4.7,
    reviewCount: 2640,
    stock: 'in-stock',
    badge: 'New',
    features: [
      'Always-on Retina LTPO OLED display',
      'Blood oxygen & ECG app',
      'Hypertension notifications',
      'Up to 18 hours battery life',
      'Crash Detection & Fall Detection',
    ],
    specs: {
      Display: 'Always-on LTPO OLED Retina',
      Case: '42mm / 46mm aluminum or titanium',
      Battery: 'Up to 18 hours (all-day)',
      'Water Resistance': '50 meters',
      Connectivity: 'Bluetooth, Wi-Fi, optional cellular',
    },
    colorways: ['Midnight', 'Starlight', 'Silver', 'Rose Gold'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    isFeatured: true,
    releaseYear: 2025,
  },
  {
    id: 'p061',
    slug: 'samsung-galaxy-watch-8',
    brand: 'Samsung',
    name: 'Galaxy Watch 8',
    category: 'smartwatches',
    shortDescription: 'Sleek design with advanced sleep and fitness coaching.',
    description:
      'Galaxy Watch 8 refines Samsung’s wearable lineup with a slimmer bezel, advanced sleep apnea detection and personalized fitness coaching powered by Galaxy AI.',
    price: 349,
    originalPrice: 399,
    rating: 4.5,
    reviewCount: 970,
    stock: 'in-stock',
    features: [
      'Sapphire crystal display',
      'Advanced sleep coaching & apnea detection',
      'Body composition analysis',
      'Up to 40 hours battery life',
      'Google Wear OS with One UI Watch',
    ],
    specs: {
      Display: '1.5" Super AMOLED',
      Case: '40mm / 44mm aluminum',
      Battery: 'Up to 40 hours',
      'Water Resistance': '5ATM + IP68',
      Connectivity: 'Bluetooth, Wi-Fi, optional LTE',
    },
    colorways: ['Graphite', 'Silver', 'Sapphire'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2025,
  },
  {
    id: 'p062',
    slug: 'garmin-fenix-8',
    brand: 'Garmin',
    name: 'Fenix 8',
    category: 'smartwatches',
    shortDescription: 'Rugged multisport GPS watch with AMOLED display.',
    description:
      'Garmin Fenix 8 is built for serious athletes and adventurers, combining a rugged titanium-reinforced case, precise multi-band GPS and up to 16 days of battery life with a vivid AMOLED display.',
    price: 999,
    rating: 4.8,
    reviewCount: 410,
    stock: 'low-stock',
    features: [
      'AMOLED touchscreen with solar options',
      'Multi-band GPS with SatIQ technology',
      'Up to 16 days battery life (smartwatch mode)',
      'Built-in flashlight',
      'Advanced training & recovery metrics',
    ],
    specs: {
      Display: '1.4" AMOLED',
      Case: 'Titanium-reinforced, 47mm',
      Battery: 'Up to 16 days (smartwatch mode)',
      'Water Resistance': '10 ATM',
      Connectivity: 'Bluetooth, Wi-Fi, ANT+',
    },
    colorways: ['Slate Gray', 'Carbon Gray Titanium'],
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p063',
    slug: 'apple-watch-ultra-3',
    brand: 'Apple',
    name: 'Apple Watch Ultra 3',
    category: 'smartwatches',
    shortDescription: 'Satellite connectivity, extreme battery, titanium case.',
    description:
      'Apple Watch Ultra 3 is engineered for extremes, with a rugged titanium case, satellite connectivity for emergencies off the grid, and the longest battery life of any Apple Watch.',
    price: 799,
    rating: 4.8,
    reviewCount: 690,
    stock: 'in-stock',
    badge: 'New',
    features: [
      '49mm titanium case',
      'Satellite connectivity',
      'Up to 42 hours battery life (72 in low power mode)',
      'Night Mode always-on display',
      'Precision dual-frequency GPS',
    ],
    specs: {
      Display: 'Always-on LTPO OLED Retina',
      Case: '49mm titanium',
      Battery: 'Up to 42 hours',
      'Water Resistance': '100 meters, EN13319 dive rated',
      Connectivity: 'Bluetooth, Wi-Fi, LTE, satellite',
    },
    colorways: ['Natural Titanium', 'Black Titanium'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2025,
  },
  {
    id: 'p064',
    slug: 'xiaomi-watch-s4',
    brand: 'Xiaomi',
    name: 'Watch S4',
    category: 'smartwatches',
    shortDescription: 'Elegant AMOLED smartwatch with 15-day battery.',
    description:
      'Xiaomi Watch S4 pairs a classic circular AMOLED display with comprehensive health tracking and up to 15 days of battery life, all at an accessible price point.',
    price: 179,
    originalPrice: 199,
    rating: 4.3,
    reviewCount: 380,
    stock: 'in-stock',
    features: [
      '1.43" AMOLED display',
      'Dual-band GPS',
      'Up to 15 days battery life',
      '150+ sport modes',
      'Blood oxygen & heart rate monitoring',
    ],
    specs: {
      Display: '1.43" AMOLED',
      Case: '46mm aluminum alloy',
      Battery: 'Up to 15 days (typical use)',
      'Water Resistance': '5 ATM',
      Connectivity: 'Bluetooth 5.4',
    },
    colorways: ['Black', 'Silver'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },

  // ---------------- CAMERAS ----------------
  {
    id: 'p070',
    slug: 'sony-alpha-a7-v',
    brand: 'Sony',
    name: 'Alpha A7 V',
    category: 'cameras',
    shortDescription: 'Full-frame hybrid mirrorless for photo and video pros.',
    description:
      'The Sony Alpha A7 V is a versatile full-frame mirrorless camera built for hybrid shooters, combining exceptional autofocus, in-body stabilization and 8K video capability in a refined, weather-sealed body.',
    price: 2499,
    rating: 4.8,
    reviewCount: 320,
    stock: 'in-stock',
    badge: 'Editor\'s Pick',
    features: [
      '33MP full-frame BSI sensor',
      '8K30p / 4K120p video recording',
      'AI-powered subject recognition autofocus',
      'In-body 5-axis image stabilization',
      'Weather-sealed magnesium alloy body',
    ],
    specs: {
      Sensor: '33MP full-frame BSI CMOS',
      Video: '8K30p, 4K120p',
      ISO: '100–51,200 (expandable)',
      Autofocus: '759-point phase detection, AI subject recognition',
      Mount: 'Sony E-mount',
    },
    colorways: ['Black'],
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    isFeatured: true,
    releaseYear: 2025,
  },
  {
    id: 'p071',
    slug: 'canon-eos-r6-mark-iii',
    brand: 'Canon',
    name: 'EOS R6 Mark III',
    category: 'cameras',
    shortDescription: 'Fast, versatile full-frame mirrorless for creators.',
    description:
      'Canon EOS R6 Mark III balances speed and versatility with rapid burst shooting, advanced Dual Pixel autofocus and rich, natural color science trusted by professionals worldwide.',
    price: 2199,
    originalPrice: 2399,
    rating: 4.7,
    reviewCount: 280,
    stock: 'in-stock',
    features: [
      '24.2MP full-frame CMOS sensor',
      'Up to 40fps electronic shutter burst',
      'Dual Pixel CMOS AF II',
      'In-body image stabilization, up to 8.5 stops',
      '4K60p oversampled video',
    ],
    specs: {
      Sensor: '24.2MP full-frame CMOS',
      Video: '4K60p oversampled',
      Burst: 'Up to 40fps (electronic shutter)',
      Autofocus: 'Dual Pixel CMOS AF II',
      Mount: 'Canon RF mount',
    },
    colorways: ['Black'],
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p072',
    slug: 'sony-zv-e10-ii',
    brand: 'Sony',
    name: 'ZV-E10 II',
    category: 'cameras',
    shortDescription: 'Compact vlogging camera with interchangeable lenses.',
    description:
      'Sony ZV-E10 II is purpose-built for content creators, offering interchangeable-lens flexibility, a fully articulating screen and intuitive controls like Product Showcase and Background Defocus.',
    price: 999,
    rating: 4.6,
    reviewCount: 450,
    stock: 'in-stock',
    features: [
      '26MP APS-C sensor',
      '4K60p oversampled video',
      'Fully articulating vlog-friendly screen',
      'Product Showcase autofocus setting',
      'Built-in directional 3-capsule mic',
    ],
    specs: {
      Sensor: '26MP APS-C Exmor R CMOS',
      Video: '4K60p, Full HD 120p',
      Autofocus: 'Fast Hybrid AF, real-time tracking',
      Mount: 'Sony E-mount',
    },
    colorways: ['Black', 'White'],
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2023,
  },
  {
    id: 'p073',
    slug: 'gopro-hero-13-black',
    brand: 'GoPro',
    name: 'HERO 13 Black',
    category: 'cameras',
    shortDescription: 'Ultra-stabilized 5.3K action camera with magnetic mounts.',
    description:
      'GoPro HERO 13 Black delivers ultra-stabilized 5.3K video with HyperSmooth 6.0, a new magnetic mounting system for faster setup, and interchangeable lenses for creative flexibility.',
    price: 429,
    originalPrice: 479,
    rating: 4.6,
    reviewCount: 890,
    stock: 'in-stock',
    features: [
      '5.3K60 / 4K120 video capture',
      'HyperSmooth 6.0 stabilization',
      'Magnetic quick-release mounting',
      'Waterproof to 10m without housing',
      'Interchangeable lens system',
    ],
    specs: {
      Video: '5.3K60, 4K120, 2.7K240',
      Photo: '27MP stills',
      'Water Resistance': '10m without housing',
      Stabilization: 'HyperSmooth 6.0',
      Battery: 'Enduro battery included',
    },
    colorways: ['Black'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p074',
    slug: 'canon-powershot-g7-x-mark-iii',
    brand: 'Canon',
    name: 'PowerShot G7 X Mark III',
    category: 'cameras',
    shortDescription: 'Pocketable creator compact with live-streaming support.',
    description:
      'Canon PowerShot G7 X Mark III packs a large 1" sensor and bright zoom lens into a pocketable body, with built-in live-streaming support making it a favorite among vloggers.',
    price: 749,
    rating: 4.5,
    reviewCount: 610,
    stock: 'out-of-stock',
    features: [
      '20.1MP 1" stacked CMOS sensor',
      '4K30p video recording',
      'Built-in YouTube live streaming',
      'Flip-up 3" touchscreen',
      '4.2x optical zoom, f/1.8-2.8 lens',
    ],
    specs: {
      Sensor: '20.1MP 1" stacked CMOS',
      Video: '4K30p',
      Lens: '24-100mm equiv., f/1.8-2.8',
      Screen: '3" flip-up touchscreen',
    },
    colorways: ['Black'],
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2019,
  },

  // ---------------- ACCESSORIES ----------------
  {
    id: 'p080',
    slug: 'apple-magsafe-charger',
    brand: 'Apple',
    name: 'MagSafe Charger',
    category: 'accessories',
    shortDescription: 'Perfectly aligned wireless charging for iPhone.',
    description:
      'The Apple MagSafe Charger snaps perfectly into place for faster wireless charging, compatible with all MagSafe-enabled iPhone models and select accessories.',
    price: 49,
    rating: 4.5,
    reviewCount: 4200,
    stock: 'in-stock',
    features: [
      'Magnetic alignment for optimal charging',
      'Up to 15W charging speed',
      'Compatible with MagSafe cases',
      '1m woven USB-C cable',
    ],
    specs: {
      Output: 'Up to 15W',
      Cable: '1m USB-C, braided',
      Compatibility: 'iPhone 12 and later',
    },
    colorways: ['White'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2020,
  },
  {
    id: 'p081',
    slug: 'logitech-mx-master-4',
    brand: 'Logitech',
    name: 'MX Master 4 Wireless Mouse',
    category: 'accessories',
    shortDescription: 'Precision productivity mouse with haptic feedback.',
    description:
      'Logitech MX Master 4 refines the benchmark productivity mouse with haptic feedback, a quieter click mechanism, and the acclaimed MagSpeed electromagnetic scroll wheel.',
    price: 119,
    rating: 4.7,
    reviewCount: 1560,
    stock: 'in-stock',
    badge: 'Bestseller',
    features: [
      'MagSpeed electromagnetic scroll wheel',
      'Haptic feedback on click',
      'Quiet Click technology',
      'Up to 70 days battery life',
      'Works across up to 3 devices',
    ],
    specs: {
      Connectivity: 'Bluetooth, Logi Bolt USB receiver',
      Battery: 'Up to 70 days per charge',
      DPI: 'Up to 8,000',
      Buttons: '8 programmable',
    },
    colorways: ['Graphite', 'Pale Gray'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p082',
    slug: 'anker-737-power-bank',
    brand: 'Anker',
    name: '737 Power Bank (PowerCore 24K)',
    category: 'accessories',
    shortDescription: '24,000mAh with 140W bidirectional fast charging.',
    description:
      'Anker 737 Power Bank delivers massive 24,000mAh capacity with 140W bidirectional charging, fast enough to charge a laptop, plus a smart digital display showing real-time power stats.',
    price: 99,
    originalPrice: 129,
    rating: 4.6,
    reviewCount: 2870,
    stock: 'in-stock',
    features: [
      '24,000mAh capacity',
      'Up to 140W bidirectional fast charging',
      'Smart digital display',
      'Charges 3 devices simultaneously',
      'Recharges fully in about 1 hour',
    ],
    specs: {
      Capacity: '24,000mAh / 87Wh',
      Output: 'Up to 140W (USB-C)',
      Ports: '2x USB-C, 1x USB-A',
      Weight: '490g',
    },
    colorways: ['Black'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2022,
  },
  {
    id: 'p083',
    slug: 'logitech-mx-keys-s',
    brand: 'Logitech',
    name: 'MX Keys S Wireless Keyboard',
    category: 'accessories',
    shortDescription: 'Smart illumination, stable typing, multi-device.',
    description:
      'Logitech MX Keys S offers a refined typing experience with smart backlighting that adapts to your surroundings and hand position, plus seamless switching across up to three devices.',
    price: 109,
    rating: 4.7,
    reviewCount: 1340,
    stock: 'in-stock',
    features: [
      'Smart, perfect-stroke keys',
      'Adaptive smart backlighting',
      'Works across up to 3 devices',
      'Up to 10 days battery life (backlit)',
      'Logi Options+ customization',
    ],
    specs: {
      Connectivity: 'Bluetooth, Logi Bolt USB receiver',
      Battery: 'Up to 10 days (backlit on)',
      Layout: 'Full-size with numpad',
    },
    colorways: ['Graphite', 'Pale Gray'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2023,
  },
  {
    id: 'p084',
    slug: 'apple-pencil-pro',
    brand: 'Apple',
    name: 'Apple Pencil Pro',
    category: 'accessories',
    shortDescription: 'Precision drawing with squeeze, haptics and barrel roll.',
    description:
      'Apple Pencil Pro adds new levels of interactivity to iPad, with squeeze gestures, haptic feedback and barrel roll for expressive shading, alongside pixel-perfect precision.',
    price: 129,
    rating: 4.6,
    reviewCount: 980,
    stock: 'in-stock',
    features: [
      'Squeeze gesture for tool palette',
      'Haptic feedback via Taptic Engine',
      'Barrel roll for shading and shaping',
      'Find My support',
      'Magnetic attach, pair and charge',
    ],
    specs: {
      Compatibility: 'iPad Pro (M4), iPad Air (M2 and later)',
      Charging: 'Magnetic wireless',
      Sensors: 'Pressure, tilt, barrel roll',
    },
    colorways: ['White'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p085',
    slug: 'samsung-45w-usb-c-charger',
    brand: 'Samsung',
    name: '45W USB-C Super Fast Charger',
    category: 'accessories',
    shortDescription: 'Compact fast charger for Galaxy phones, tablets and more.',
    description:
      'The Samsung 45W USB-C Super Fast Charger delivers rapid top-ups for Galaxy smartphones, tablets and select laptops in a compact, travel-friendly design.',
    price: 39,
    rating: 4.4,
    reviewCount: 1120,
    stock: 'in-stock',
    features: [
      'Up to 45W Super Fast Charging 2.0',
      'Compact, travel-friendly design',
      'Compatible with USB Power Delivery devices',
      'Built-in safety protections',
    ],
    specs: {
      Output: 'Up to 45W USB-C PD',
      Compatibility: 'Galaxy S/Note/Tab series and USB-PD devices',
    },
    colorways: ['White'],
    warranty: STANDARD_WARRANTY,
    delivery: FAST_DELIVERY,
    releaseYear: 2021,
  },

  // ---------------- COMPONENTS ----------------
  {
    id: 'p090',
    slug: 'nvidia-geforce-rtx-5080',
    brand: 'NVIDIA',
    name: 'GeForce RTX 5080',
    category: 'components',
    shortDescription: 'Next-gen Blackwell architecture for 4K ray-traced gaming.',
    description:
      'The NVIDIA GeForce RTX 5080 harnesses the Blackwell architecture with next-generation DLSS and ray tracing cores, delivering exceptional 4K gaming and creative performance.',
    price: 999,
    rating: 4.7,
    reviewCount: 380,
    stock: 'low-stock',
    badge: 'New',
    features: [
      'NVIDIA Blackwell architecture',
      '16GB GDDR7 memory',
      'DLSS 4 with multi-frame generation',
      '4th Gen Ray Tracing Cores',
      'PCIe 5.0 support',
    ],
    specs: {
      Memory: '16GB GDDR7',
      'Boost Clock': 'Up to 2.6 GHz',
      Interface: 'PCIe 5.0 x16',
      Outputs: '3x DisplayPort 2.1, 1x HDMI 2.1b',
      'Power Draw': '360W (750W PSU recommended)',
    },
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    isFeatured: true,
    releaseYear: 2025,
  },
  {
    id: 'p091',
    slug: 'corsair-vengeance-32gb-ddr5',
    brand: 'Corsair',
    name: 'Vengeance 32GB DDR5-6000 RAM Kit',
    category: 'components',
    shortDescription: 'High-performance DDR5 memory with aluminum heat spreaders.',
    description:
      'Corsair Vengeance DDR5 delivers a significant leap in bandwidth and speed over previous-gen memory, engineered with a durable all-aluminum heat spreader for efficient thermal dissipation.',
    price: 139,
    originalPrice: 159,
    rating: 4.7,
    reviewCount: 2100,
    stock: 'in-stock',
    features: [
      '32GB (2x16GB) DDR5-6000 kit',
      'Aluminum heat spreader for thermal dissipation',
      'Intel XMP 3.0 support',
      'Screened for maximum compatibility',
    ],
    specs: {
      Capacity: '32GB (2x16GB)',
      Speed: 'DDR5-6000 (PC5-48000)',
      Latency: 'CL36',
      Voltage: '1.35V',
    },
    colorways: ['Black', 'White'],
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2023,
  },
  {
    id: 'p092',
    slug: 'samsung-990-pro-2tb-ssd',
    brand: 'Samsung',
    name: '990 Pro 2TB NVMe SSD',
    category: 'components',
    shortDescription: 'PCIe 4.0 SSD with blazing sequential speeds.',
    description:
      'Samsung 990 Pro pushes PCIe 4.0 to its limits, with sequential read speeds up to 7,450MB/s, making it ideal for gaming, content creation and demanding workstation tasks.',
    price: 179,
    originalPrice: 219,
    rating: 4.8,
    reviewCount: 3400,
    stock: 'in-stock',
    badge: 'Bestseller',
    features: [
      'Up to 7,450MB/s sequential read',
      'PCIe 4.0 x4, NVMe 2.0',
      'Samsung V-NAND with in-house controller',
      'Nickel-coated controller for heat management',
      'Samsung Magician software support',
    ],
    specs: {
      Capacity: '2TB',
      Interface: 'PCIe 4.0 x4, NVMe 2.0',
      'Read Speed': 'Up to 7,450 MB/s',
      'Write Speed': 'Up to 6,900 MB/s',
      Form: 'M.2 2280',
    },
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2022,
  },
  {
    id: 'p093',
    slug: 'intel-core-i9-15900k',
    brand: 'Intel',
    name: 'Core i9-15900K',
    category: 'components',
    shortDescription: 'Flagship desktop processor for gaming and creation.',
    description:
      'Intel Core i9-15900K is Intel’s flagship unlocked desktop processor, delivering exceptional multi-threaded performance for content creation alongside class-leading gaming frame rates.',
    price: 589,
    rating: 4.6,
    reviewCount: 640,
    stock: 'in-stock',
    features: [
      '24 cores (8P + 16E) / 32 threads',
      'Up to 6.0 GHz max turbo frequency',
      'Unlocked for overclocking',
      'Intel UHD integrated graphics',
      'Compatible with DDR5 memory',
    ],
    specs: {
      Cores: '24 (8P + 16E) / 32 threads',
      'Max Turbo': 'Up to 6.0 GHz',
      Cache: '36MB Intel Smart Cache',
      TDP: '125W base / 253W max turbo',
      Socket: 'LGA 1851',
    },
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2024,
  },
  {
    id: 'p094',
    slug: 'corsair-rm1000e-psu',
    brand: 'Corsair',
    name: 'RM1000e Power Supply',
    category: 'components',
    shortDescription: '1000W 80 PLUS Gold fully modular PSU.',
    description:
      'Corsair RM1000e provides clean, reliable power with 80 PLUS Gold efficiency, fully modular cabling for tidy builds, and a near-silent zero RPM fan mode under light loads.',
    price: 149,
    rating: 4.6,
    reviewCount: 890,
    stock: 'in-stock',
    features: [
      '1000W continuous power output',
      '80 PLUS Gold certified efficiency',
      'Fully modular flat cables',
      'Zero RPM fan mode for near-silent operation',
      '10-year warranty',
    ],
    specs: {
      Wattage: '1000W',
      Efficiency: '80 PLUS Gold',
      Modular: 'Fully modular',
      Fan: '135mm, Zero RPM mode',
    },
    warranty: '10-Year Manufacturer Warranty',
    delivery: STANDARD_DELIVERY,
    releaseYear: 2023,
  },
  {
    id: 'p095',
    slug: 'asus-rog-strix-b850-f',
    brand: 'ASUS',
    name: 'ROG Strix B850-F Gaming WiFi Motherboard',
    category: 'components',
    shortDescription: 'AM5 motherboard with PCIe 5.0 and WiFi 7.',
    description:
      'ASUS ROG Strix B850-F Gaming WiFi delivers robust power delivery, PCIe 5.0 connectivity and WiFi 7 for next-generation AMD Ryzen builds, wrapped in ROG’s signature aesthetic.',
    price: 259,
    rating: 4.5,
    reviewCount: 310,
    stock: 'in-stock',
    features: [
      'AMD AM5 socket, Ryzen 9000/8000/7000 support',
      'PCIe 5.0 x16 and M.2 slots',
      'WiFi 7 and 2.5Gb Ethernet',
      'Robust 14+2 power stages',
      'Aura Sync RGB lighting',
    ],
    specs: {
      Socket: 'AM5',
      Chipset: 'AMD B850',
      Memory: 'DDR5, up to 8000MHz (OC)',
      Connectivity: 'WiFi 7, 2.5Gb LAN',
      'Expansion Slots': 'PCIe 5.0 x16, 3x M.2',
    },
    warranty: EXTENDED_WARRANTY,
    delivery: STANDARD_DELIVERY,
    releaseYear: 2024,
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4) {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, count);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.isFeatured);
}

export function getDealProducts() {
  return products.filter((p) => p.originalPrice && p.originalPrice > p.price);
}

export function discountPercent(p: Product) {
  if (!p.originalPrice) return 0;
  return Math.round(((p.originalPrice - p.price) / p.originalPrice) * 100);
}

export const brands = Array.from(new Set(products.map((p) => p.brand))).sort();
